Traceback (most recent call last):
  File "/Python/main.py", line 6, in <module>
    from VerCode import get_vercode
  File "/Python/VerCode.py", line 2, in <module>
    import cv2
  File "/Python/打卡_venv/lib/python3.7/site-packages/cv2/__init__.py", line 5, in <module>
    from .cv2 import *
ImportError: libGL.so.1: cannot open shared object file: No such file or directory
Traceback (most recent call last):
  File "/Python/打卡_venv/lib/python3.7/site-packages/selenium/webdriver/common/service.py", line 76, in start
    stdin=PIPE)
  File "/www/server/panel/pyenv/lib/python3.7/subprocess.py", line 800, in __init__
    restore_signals, start_new_session)
  File "/www/server/panel/pyenv/lib/python3.7/subprocess.py", line 1551, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
PermissionError: [Errno 13] Permission denied: 'chromedriver'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Python/main.py", line 117, in <module>
    fun()
  File "/Python/main.py", line 28, in fun
    wd = webdriver.Chrome(options=chrome_options)
  File "/Python/打卡_venv/lib/python3.7/site-packages/selenium/webdriver/chrome/webdriver.py", line 73, in __init__
    self.service.start()
  File "/Python/打卡_venv/lib/python3.7/site-packages/selenium/webdriver/common/service.py", line 88, in start
    os.path.basename(self.path), self.start_error_message)
selenium.common.exceptions.WebDriverException: Message: 'chromedriver' executable may have wrong permissions. Please see https://sites.google.com/a/chromium.org/chromedriver/home

Traceback (most recent call last):
  File "/Python/打卡_venv/lib/python3.7/site-packages/selenium/webdriver/common/service.py", line 76, in start
    stdin=PIPE)
  File "/www/server/panel/pyenv/lib/python3.7/subprocess.py", line 800, in __init__
    restore_signals, start_new_session)
  File "/www/server/panel/pyenv/lib/python3.7/subprocess.py", line 1551, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
PermissionError: [Errno 13] Permission denied: 'chromedriver'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Python/main.py", line 117, in <module>
    fun()
  File "/Python/main.py", line 28, in fun
    wd = webdriver.Chrome(options=chrome_options)
  File "/Python/打卡_venv/lib/python3.7/site-packages/selenium/webdriver/chrome/webdriver.py", line 73, in __init__
    self.service.start()
  File "/Python/打卡_venv/lib/python3.7/site-packages/selenium/webdriver/common/service.py", line 88, in start
    os.path.basename(self.path), self.start_error_message)
selenium.common.exceptions.WebDriverException: Message: 'chromedriver' executable may have wrong permissions. Please see https://sites.google.com/a/chromium.org/chromedriver/home

wp成功进入每日健康打卡界面！
Traceback (most recent call last):
  File "/Python/main.py", line 117, in <module>
    fun()
  File "/Python/main.py", line 74, in fun
    temper1_input = wd.find_element_by_xpath('//input[@id="xwwd"]')
  File "/Python/打卡_venv/lib/python3.7/site-packages/selenium/webdriver/remote/webdriver.py", line 394, in find_element_by_xpath
    return self.find_element(by=By.XPATH, value=xpath)
  File "/Python/打卡_venv/lib/python3.7/site-packages/selenium/webdriver/remote/webdriver.py", line 978, in find_element
    'value': value})['value']
  File "/Python/打卡_venv/lib/python3.7/site-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "/Python/打卡_venv/lib/python3.7/site-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.NoSuchElementException: Message: no such element: Unable to locate element: {"method":"xpath","selector":"//input[@id="xwwd"]"}
  (Session info: headless chrome=88.0.4324.150)

wp成功进入每日健康打卡界面！
Traceback (most recent call last):
  File "/Python/main.py", line 117, in <module>
    fun()
  File "/Python/main.py", line 74, in fun
    temper1_input = wd.find_element_by_xpath('//input[@id="xwwd"]')
  File "/Python/打卡_venv/lib/python3.7/site-packages/selenium/webdriver/remote/webdriver.py", line 394, in find_element_by_xpath
    return self.find_element(by=By.XPATH, value=xpath)
  File "/Python/打卡_venv/lib/python3.7/site-packages/selenium/webdriver/remote/webdriver.py", line 978, in find_element
    'value': value})['value']
  File "/Python/打卡_venv/lib/python3.7/site-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "/Python/打卡_venv/lib/python3.7/site-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.NoSuchElementException: Message: no such element: Unable to locate element: {"method":"xpath","selector":"//input[@id="xwwd"]"}
  (Session info: headless chrome=88.0.4324.150)

libpng error: Read Error
Traceback (most recent call last):
  File "/Python/main.py", line 117, in <module>
    fun()
  File "/Python/main.py", line 36, in fun
    ver_code = get_vercode(wd, captchaImg)
  File "/Python/VerCode.py", line 25, in get_vercode
    img = img[y1:y2, x1:x2, :]
TypeError: 'NoneType' object is not subscriptable
libpng error: Read Error
Traceback (most recent call last):
  File "/Python/main.py", line 117, in <module>
    fun()
  File "/Python/main.py", line 36, in fun
    ver_code = get_vercode(wd, captchaImg)
  File "/Python/VerCode.py", line 25, in get_vercode
    img = img[y1:y2, x1:x2, :]
TypeError: 'NoneType' object is not subscriptable
wp成功进入每日健康打卡界面！
Traceback (most recent call last):
  File "/Python/main.py", line 117, in <module>
    fun()
  File "/Python/main.py", line 74, in fun
    temper1_input = wd.find_element_by_xpath('//input[@id="xwwd"]')
  File "/Python/打卡_venv/lib/python3.7/site-packages/selenium/webdriver/remote/webdriver.py", line 394, in find_element_by_xpath
    return self.find_element(by=By.XPATH, value=xpath)
  File "/Python/打卡_venv/lib/python3.7/site-packages/selenium/webdriver/remote/webdriver.py", line 978, in find_element
    'value': value})['value']
  File "/Python/打卡_venv/lib/python3.7/site-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "/Python/打卡_venv/lib/python3.7/site-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.NoSuchElementException: Message: no such element: Unable to locate element: {"method":"xpath","selector":"//input[@id="xwwd"]"}
  (Session info: headless chrome=88.0.4324.150)

/Python/打卡_venv/bin/python: can't find '__main__' module in '/Python'
/Python/打卡_venv/bin/python: can't find '__main__' module in '/Python'
/Python/打卡_venv/bin/python: can't find '__main__' module in '/Python'
/Python/打卡_venv/bin/python: can't find '__main__' module in '/Python'
Traceback (most recent call last):
  File "/Python/AipOcr.py", line 29, in VCodeRec
    word = ocr_result['words_result'][0]['words'].replace(" ", "")
KeyError: 'words_result'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Python/main.py", line 117, in <module>
    fun()
  File "/Python/main.py", line 36, in fun
    ver_code = get_vercode(wd, captchaImg)
  File "/Python/VerCode.py", line 28, in get_vercode
    word = VCodeRec('data/captcha.jpg')
  File "/Python/AipOcr.py", line 33, in VCodeRec
    return word
UnboundLocalError: local variable 'word' referenced before assignment
wp成功进入每日健康打卡界面！
Traceback (most recent call last):
  File "/Python/main.py", line 117, in <module>
    fun()
  File "/Python/main.py", line 74, in fun
    temper1_input = wd.find_element_by_xpath('//input[@id="xwwd"]')
  File "/Python/打卡_venv/lib/python3.7/site-packages/selenium/webdriver/remote/webdriver.py", line 394, in find_element_by_xpath
    return self.find_element(by=By.XPATH, value=xpath)
  File "/Python/打卡_venv/lib/python3.7/site-packages/selenium/webdriver/remote/webdriver.py", line 978, in find_element
    'value': value})['value']
  File "/Python/打卡_venv/lib/python3.7/site-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "/Python/打卡_venv/lib/python3.7/site-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.NoSuchElementException: Message: no such element: Unable to locate element: {"method":"xpath","selector":"//input[@id="xwwd"]"}
  (Session info: headless chrome=88.0.4324.150)

Traceback (most recent call last):
  File "/Python/main.py", line 6, in <module>
    from VerCode import get_vercode
  File "/Python/VerCode.py", line 2, in <module>
    import cv2
ModuleNotFoundError: No module named 'cv2'
Traceback (most recent call last):
  File "/Python/main.py", line 6, in <module>
    from VerCode import get_vercode
  File "/Python/VerCode.py", line 2, in <module>
    import cv2
ModuleNotFoundError: No module named 'cv2'
wp成功进入每日健康打卡界面！
Traceback (most recent call last):
  File "/Python/main.py", line 117, in <module>
    fun()
  File "/Python/main.py", line 74, in fun
    temper1_input = wd.find_element_by_xpath('//input[@id="xwwd"]')
  File "/Python/打卡_venv/lib/python3.7/site-packages/selenium/webdriver/remote/webdriver.py", line 394, in find_element_by_xpath
    return self.find_element(by=By.XPATH, value=xpath)
  File "/Python/打卡_venv/lib/python3.7/site-packages/selenium/webdriver/remote/webdriver.py", line 978, in find_element
    'value': value})['value']
  File "/Python/打卡_venv/lib/python3.7/site-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "/Python/打卡_venv/lib/python3.7/site-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.NoSuchElementException: Message: no such element: Unable to locate element: {"method":"xpath","selector":"//input[@id="xwwd"]"}
  (Session info: headless chrome=88.0.4324.150)

wp成功进入每日健康打卡界面！
Traceback (most recent call last):
  File "/Python/main.py", line 117, in <module>
    fun()
  File "/Python/main.py", line 74, in fun
    temper1_input = wd.find_element_by_xpath('//input[@id="xwwd"]')
  File "/Python/打卡_venv/lib/python3.7/site-packages/selenium/webdriver/remote/webdriver.py", line 394, in find_element_by_xpath
    return self.find_element(by=By.XPATH, value=xpath)
  File "/Python/打卡_venv/lib/python3.7/site-packages/selenium/webdriver/remote/webdriver.py", line 978, in find_element
    'value': value})['value']
  File "/Python/打卡_venv/lib/python3.7/site-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "/Python/打卡_venv/lib/python3.7/site-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.NoSuchElementException: Message: no such element: Unable to locate element: {"method":"xpath","selector":"//input[@id="xwwd"]"}
  (Session info: headless chrome=88.0.4324.150)

/Python/123_venv/bin/python: can't find '__main__' module in '/Python'
/Python/123_venv/bin/python: can't find '__main__' module in '/Python'
/Python/123_venv/bin/python: can't find '__main__' module in '/Python'
wp成功进入每日健康打卡界面！
Traceback (most recent call last):
  File "/Python/main.py", line 117, in <module>
    fun()
  File "/Python/main.py", line 74, in fun
    temper1_input = wd.find_element_by_xpath('//input[@id="xwwd"]')
  File "/Python/123_venv/lib/python3.7/site-packages/selenium/webdriver/remote/webdriver.py", line 394, in find_element_by_xpath
    return self.find_element(by=By.XPATH, value=xpath)
  File "/Python/123_venv/lib/python3.7/site-packages/selenium/webdriver/remote/webdriver.py", line 978, in find_element
    'value': value})['value']
  File "/Python/123_venv/lib/python3.7/site-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "/Python/123_venv/lib/python3.7/site-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.NoSuchElementException: Message: no such element: Unable to locate element: {"method":"xpath","selector":"//input[@id="xwwd"]"}
  (Session info: headless chrome=88.0.4324.150)

wp成功进入每日健康打卡界面！
Traceback (most recent call last):
  File "/Python/main.py", line 117, in <module>
    fun()
  File "/Python/main.py", line 74, in fun
    temper1_input = wd.find_element_by_xpath('//input[@id="xwwd"]')
  File "/Python/123_venv/lib/python3.7/site-packages/selenium/webdriver/remote/webdriver.py", line 394, in find_element_by_xpath
    return self.find_element(by=By.XPATH, value=xpath)
  File "/Python/123_venv/lib/python3.7/site-packages/selenium/webdriver/remote/webdriver.py", line 978, in find_element
    'value': value})['value']
  File "/Python/123_venv/lib/python3.7/site-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "/Python/123_venv/lib/python3.7/site-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.NoSuchElementException: Message: no such element: Unable to locate element: {"method":"xpath","selector":"//input[@id="xwwd"]"}
  (Session info: headless chrome=88.0.4324.150)

wp成功进入每日健康打卡界面！
Traceback (most recent call last):
  File "/Python/main.py", line 117, in <module>
    fun()
  File "/Python/main.py", line 74, in fun
    temper1_input = wd.find_element_by_xpath('//input[@id="xwwd"]')
  File "/Python/123_venv/lib/python3.7/site-packages/selenium/webdriver/remote/webdriver.py", line 394, in find_element_by_xpath
    return self.find_element(by=By.XPATH, value=xpath)
  File "/Python/123_venv/lib/python3.7/site-packages/selenium/webdriver/remote/webdriver.py", line 978, in find_element
    'value': value})['value']
  File "/Python/123_venv/lib/python3.7/site-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "/Python/123_venv/lib/python3.7/site-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.NoSuchElementException: Message: no such element: Unable to locate element: {"method":"xpath","selector":"//input[@id="xwwd"]"}
  (Session info: headless chrome=88.0.4324.150)

wp成功进入每日健康打卡界面！
Traceback (most recent call last):
  File "/Python/main.py", line 117, in <module>
    fun()
  File "/Python/main.py", line 74, in fun
    temper1_input = wd.find_element_by_xpath('//input[@id="xwwd"]')
  File "/Python/123_venv/lib/python3.7/site-packages/selenium/webdriver/remote/webdriver.py", line 394, in find_element_by_xpath
    return self.find_element(by=By.XPATH, value=xpath)
  File "/Python/123_venv/lib/python3.7/site-packages/selenium/webdriver/remote/webdriver.py", line 978, in find_element
    'value': value})['value']
  File "/Python/123_venv/lib/python3.7/site-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "/Python/123_venv/lib/python3.7/site-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.NoSuchElementException: Message: no such element: Unable to locate element: {"method":"xpath","selector":"//input[@id="xwwd"]"}
  (Session info: headless chrome=88.0.4324.150)

